### ISSUE TITLE
Allow Hypothetically Exempting Assignments

### ISSUE THREAD

**Issue by gary-kim** [sas-fossdev/saspes#2]
It would be nice to be able to hypothetically exempt assignments from a course to see how this would change the final percent and grade of the course.

This would require somehow figuring out what the weighting of the assignment is. I'm not sure how to do this yet.

**Comment by insertcustomname** [comment]
If theres no way to figure out the weightage of assignments perhaps allow users to simulate exempting an assignment and specify the weightage themselves.
