### ISSUE TITLE
Firefox update script is broken

### ISSUE THREAD

**Issue by fillnye** [sas-fossdev/saspes#311]
**Extension Version**: 0.25-0.26

The JSON file [here](https://updates.garykim.dev/firefox/saspowerschoolff/updates.json) is not configured with the newest version.

### Describe steps to reproduce the error

Install version 0.24 or 0.25 on Firefox and try to update it to the newest version by disabling auto update and pressing check for update.

**Comment by gary-kim** [comment]
Oh, strange. Let me take a look at the update script for that

**Comment by gary-kim** [comment]
Okay, it has now been fixed. Not sure how that happened but the crontab command for it got mangled.
