### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by gary-kim** [sas-fossdev/saspes#9]
It would be nice if SAS PES had a welcome page to introduce people to the features of the project, allow them to opt out of analytics easily, and invite them to contribute to the project. This should also include a disclaimer that this project comes with no warranty, similar to #22.

**Comment by Crystalflxme** [comment]
This is a cool idea, only issue is based on the features you suggest that this proposed welcome screen would have, it's unclear where it would fit. For example, would it be better as the pop out of the extension or on the PowerSchool login page? Also an issue with trying to get people to contribute to the project is as you might have noticed, while there are lots of users, there are very little people who can help with the needs of the project or even bother to click on any of the GitHub links you added to the extension.

I'd be happy to help you out with this suggestion if you're open to that.

**Comment by gary-kim** [comment]
Help of any kind is always appreciated!
I was thinking along the lines of a page that opens on first install. Currently, on install, the options page is opened but how about instead, we have a included webpage that allows people to select what settings they'd like and so on.
https://github.com/gary-kim/saspes/blob/1c1df8cfcfe6656954f851113fc18dcecc8b4682/src/js/background.js#L30-L35

**Comment by Crystalflxme** [comment]
This is a good start. I think that it would be a good idea to create a main control panel where its a welcome screen, an options page, and possibly more. It could be opened somewhere on PowerSchool, possibly when you click the extension button, and for sure on install. A centralized control panel is a good idea people people don't want to go looking for every type of separate page.

**Comment by Crystalflxme** [comment]
Addition to my previous comment: Spent about 15 minutes making this early design for what a centralized control panel would look like. I'm still not sure about everything (including that scaling) but the concept is there.

![sas pes](https://user-images.githubusercontent.com/43885283/75877824-7e26f400-5e53-11ea-8be1-846625f003d5.png)

**Comment by gary-kim** [comment]
@insertcustomname You were looking at making a page for last seen grades right? Do you think it could fit into this kind of page?

**Comment by insertcustomname** [comment]
Would this pop out on click of the extension icon? If it would than it might fit there. Maybe a dedicated tab titled "Last Seen Grades", it would appear blank prior to first login and would show their last seen grades after that.

**Comment by insertcustomname** [comment]
Alternative clicking on the extension could bring up a small popup, with one option being control panel which would bring up the above page, and another option "last seen grades" that would bring up a page dedicated for last seen grades.

**Comment by gary-kim** [comment]
I like the idea of another one of the buttons being on the side being for last seen grades? When there's no information saved, it could show a message saying "This page will be populated after you login to Powerschool for the first time".

I think it'd be nice to have this dashboard come up on clicking the extension button. Each page could be made it's own Vue component. The last seen grades one will probably be done first so we can use the button for that at first then just move the Vue component for last seen grades into the dashboard once it's done.

**Comment by insertcustomname** [comment]
That sounds like a good idea, I'll try and design something in Vue for that, I haven't used Vue before, are there any examples in the repository of Vue being used I can look at?

**Comment by Crystalflxme** [comment]
My opinion on the matter is when you click the extension icon you get a last seen grades menu like spoken about just now, and a link to the control panel page that would manage the rest of the extension all in one place. That would be a great way to minimize the amount of time you aren't "using" the features of the extension thus making users much more happy.

**Comment by gary-kim** [comment]
> That sounds like a good idea, I'll try and design something in Vue for that, I haven't used Vue before, are there any examples in the repository of Vue being used I can look at?

Things are slowly but surely getting migrated to Vue. I'd recommend taking a look at [HypoGrades.vue](https://github.com/gary-kim/saspes/blob/master/src/js/components/HypoGrades.vue) because it's relatively simple but there's everything in the [components](https://github.com/gary-kim/saspes/tree/master/src/js/components) directory and #112 which adds a  [ClassGrade](https://github.com/gary-kim/saspes/blob/86d2116baaed04334d10a6e42dd8891cc0dcdd31/src/js/components/ClassGrade.vue) Vue component. 

If you'd like, take a look at the [getting started guide](https://vuejs.org/v2/guide/#Getting-Started) for Vue. Also, we're using [Vue SFC](https://vuejs.org/v2/guide/single-file-components.html) in this repo.

Feel free to contact me if you want any help!

**Comment by gary-kim** [comment]
> My opinion on the matter is when you click the extension icon you get a last seen grades menu like spoken about just now, and a link to the control panel page that would manage the rest of the extension all in one place. That would be a great way to minimize the amount of time you aren't "using" the features of the extension thus making users much more happy.

I think we could just make last seen grades be a tab in your control panel and make that the default tab. What do you think?

**Comment by Crystalflxme** [comment]
I think it would be a little annoying if you had to go to a entire page just if you wanted to quickly see your grades. Another use of that would be if somebody in class (and without the teacher seeing for example) taking a peek at their grades, and if they wanted a full look on an entire page, they can just go to PowerSchool.

**Comment by gary-kim** [comment]
The point of the feature was to be able to still view grades when Powerschool is closed. I don't think we should be facilitating making it easier to peek at grades. That's just my two cents though.
